name: SemVer Release
description: This is a test

inputs:
  token:
    description: Github branch name
    default: ${{ github.token }}
  owner:
    description: repo owner
  repo:
    description: repo repo
  sha:
    description: Commitish for tag

  tag:
    description: name of tag
  draft:
    default: true 

outputs:
  id:
    description: id
  url:
    description: url
  sha:
    description: target_commitish
  update:
    description: created or update

runs:
  using: 'node12'
  main: 'dist/main.js'
