name: "Change Log"

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: name of next version
  # pull_request:
  #   branches: [master]
  #   types: [opened, reopened, synchronize]

jobs:
  create_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Create release log
        id: changelog
        uses: ./action/lerna-changelog
        with:
          next_version: ${{ github.event.inputs.next_version }}  
          
      - name: Show log
        run: echo "$RESULT"
        env:
          RESULT: ${{steps.changelog.outputs.markdown}}
