name: "Change Log"

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

jobs:
  create_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Create release log
        id: changelog
        uses: ./action/lerna-changelog

      - name: Show log
        run: echo "$RESULT"
        env:
          RESULT: ${{steps.changelog.outputs.markdown}}
