name: "Change Log"

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

jobs:
  create_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup GIT
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Create release log
        id: changelog
        uses: ./action/lerna-changelog

      - name: Show log
        run: echo "$RESULT"
        env:
          RESULT: ${{steps.changelog.outputs.markdown}}
