name: "Test labels "

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: PR info
        id: pr_info
        uses: ./action/pr-info

      - name: Add labels
        if: ${{ steps.pr_info.outputs.pushed_labels.length != 0 }}
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            await github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ${{ steps.pr_info.outputs.pushed_labels }}
            });
