name: "Test labels"

on:
    workflow_dispatch:

jobs:
  label_pr:
    runs-on: ubuntu-latest
    # needs: check_branch
    # if: ${{ needs.check_branch.outputs.type }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Create version
        id: version
        uses: $action/label-pr
